server:
  port: 8080
  tomcat:
    threads:
      max: 400
      min-spare: 50
    accept-count: 1000
    max-connections: 8192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=Asia/Seoul
    username: subway_user
    password: subway_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      minimum-idle: 20
      connection-timeout: 5000
      validation-timeout: 1000

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always